package org.jetbrains.letsPlot.raster.view

object RenderingHints {
    const val KEY_TEXT_ANTIALIASING = "TEXT_ANTIALIASING"
    const val VALUE_TEXT_ANTIALIASING_ON = "TEXT_ANTIALIASING_ON"
    const val VALUE_TEXT_ANTIALIASING_OFF = "TEXT_ANTIALIASING_OFF"

    const val KEY_OFFSCREEN_BUFFERING = "OFFSCREEN_BUFFERING"
    const val VALUE_OFFSCREEN_BUFFERING_ON = "OFFSCREEN_BUFFERING_ON"
    const val VALUE_OFFSCREEN_BUFFERING_OFF = "OFFSCREEN_BUFFERING_OFF"

    const val KEY_DEBUG_BBOXES = "DEBUG_BOUNDING_BOXES"
    const val VALUE_DEBUG_BBOXES_ON = "DEBUG_BOUNDING_BOXES_ON"
    const val VALUE_DEBUG_BBOXES_OFF = "DEBUG_BOUNDING_BOXES_OFF"
}