package jetbrains.datalore.visualization.base.svg

import jetbrains.datalore.base.values.Color

object SvgColor {
    val ALICE_BLUE: SvgColor = SvgColorKeyword("aliceblue")
    val ANTIQUE_WHITE: SvgColor = SvgColorKeyword("antiquewhite")
    val AQUA: SvgColor = SvgColorKeyword("aqua")
    val AQUAMARINE: SvgColor = SvgColorKeyword("aquamarine")
    val AZURE: SvgColor = SvgColorKeyword("azure")
    val BEIGE: SvgColor = SvgColorKeyword("beige")
    val BISQUE: SvgColor = SvgColorKeyword("bisque")
    val BLACK: SvgColor = SvgColorKeyword("black")
    val BLANCHED_ALMOND: SvgColor = SvgColorKeyword("blanchedalmond")
    val BLUE: SvgColor = SvgColorKeyword("blue")
    val BLUE_VIOLET: SvgColor = SvgColorKeyword("blueviolet")
    val BROWN: SvgColor = SvgColorKeyword("brown")
    val BURLY_WOOD: SvgColor = SvgColorKeyword("burlywood")
    val CADET_BLUE: SvgColor = SvgColorKeyword("cadetblue")
    val CHARTREUSE: SvgColor = SvgColorKeyword("chartreuse")
    val CHOCOLATE: SvgColor = SvgColorKeyword("chocolate")
    val CORAL: SvgColor = SvgColorKeyword("coral")
    val CORNFLOWER_BLUE: SvgColor = SvgColorKeyword("cornflowerblue")
    val CORNSILK: SvgColor = SvgColorKeyword("cornsilk")
    val CRIMSON: SvgColor = SvgColorKeyword("crimson")
    val CYAN: SvgColor = SvgColorKeyword("cyan")
    val DARK_BLUE: SvgColor = SvgColorKeyword("darkblue")
    val DARK_CYAN: SvgColor = SvgColorKeyword("darkcyan")
    val DARK_GOLDEN_ROD: SvgColor = SvgColorKeyword("darkgoldenrod")
    val DARK_GRAY: SvgColor = SvgColorKeyword("darkgray")
    val DARK_GREEN: SvgColor = SvgColorKeyword("darkgreen")
    val DARK_GREY: SvgColor = SvgColorKeyword("darkgrey")
    val DARK_KHAKI: SvgColor = SvgColorKeyword("darkkhaki")
    val DARK_MAGENTA: SvgColor = SvgColorKeyword("darkmagenta")
    val DARK_OLIVE_GREEN: SvgColor = SvgColorKeyword("darkolivegreen")
    val DARK_ORANGE: SvgColor = SvgColorKeyword("darkorange")
    val DARK_ORCHID: SvgColor = SvgColorKeyword("darkorchid")
    val DARK_RED: SvgColor = SvgColorKeyword("darkred")
    val DARK_SALMON: SvgColor = SvgColorKeyword("darksalmon")
    val DARK_SEA_GREEN: SvgColor = SvgColorKeyword("darkseagreen")
    val DARK_SLATE_BLUE: SvgColor = SvgColorKeyword("darkslateblue")
    val DARK_SLATE_GRAY: SvgColor = SvgColorKeyword("darkslategray")
    val DARK_SLATE_GREY: SvgColor = SvgColorKeyword("darkslategrey")
    val DARK_TURQUOISE: SvgColor = SvgColorKeyword("darkturquoise")
    val DARK_VIOLET: SvgColor = SvgColorKeyword("darkviolet")
    val DEEP_PINK: SvgColor = SvgColorKeyword("deeppink")
    val DEEP_SKY_BLUE: SvgColor = SvgColorKeyword("deepskyblue")
    val DIM_GRAY: SvgColor = SvgColorKeyword("dimgray")
    val DIM_GREY: SvgColor = SvgColorKeyword("dimgrey")
    val DODGER_BLUE: SvgColor = SvgColorKeyword("dodgerblue")
    val FIRE_BRICK: SvgColor = SvgColorKeyword("firebrick")
    val FLORAL_WHITE: SvgColor = SvgColorKeyword("floralwhite")
    val FOREST_GREEN: SvgColor = SvgColorKeyword("forestgreen")
    val FUCHSIA: SvgColor = SvgColorKeyword("fuchsia")
    val GAINSBORO: SvgColor = SvgColorKeyword("gainsboro")
    val GHOST_WHITE: SvgColor = SvgColorKeyword("ghostwhite")
    val GOLD: SvgColor = SvgColorKeyword("gold")
    val GOLDEN_ROD: SvgColor = SvgColorKeyword("goldenrod")
    val GRAY: SvgColor = SvgColorKeyword("gray")
    val GREY: SvgColor = SvgColorKeyword("grey")
    val GREEN: SvgColor = SvgColorKeyword("green")
    val GREEN_YELLOW: SvgColor = SvgColorKeyword("greenyellow")
    val HONEY_DEW: SvgColor = SvgColorKeyword("honeydew")
    val HOT_PINK: SvgColor = SvgColorKeyword("hotpink")
    val INDIAN_RED: SvgColor = SvgColorKeyword("indianred")
    val INDIGO: SvgColor = SvgColorKeyword("indigo")
    val IVORY: SvgColor = SvgColorKeyword("ivory")
    val KHAKI: SvgColor = SvgColorKeyword("khaki")
    val LAVENDER: SvgColor = SvgColorKeyword("lavender")
    val LAVENDER_BLUSH: SvgColor = SvgColorKeyword("lavenderblush")
    val LAWN_GREEN: SvgColor = SvgColorKeyword("lawngreen")
    val LEMON_CHIFFON: SvgColor = SvgColorKeyword("lemonchiffon")
    val LIGHT_BLUE: SvgColor = SvgColorKeyword("lightblue")
    val LIGHT_CORAL: SvgColor = SvgColorKeyword("lightcoral")
    val LIGHT_CYAN: SvgColor = SvgColorKeyword("lightcyan")
    val LIGHT_GOLDEN_ROD_YELLOW: SvgColor = SvgColorKeyword("lightgoldenrodyellow")
    val LIGHT_GRAY: SvgColor = SvgColorKeyword("lightgray")
    val LIGHT_GREEN: SvgColor = SvgColorKeyword("lightgreen")
    val LIGHT_GREY: SvgColor = SvgColorKeyword("lightgrey")
    val LIGHT_PINK: SvgColor = SvgColorKeyword("lightpink")
    val LIGHT_SALMON: SvgColor = SvgColorKeyword("lightsalmon")
    val LIGHT_SEA_GREEN: SvgColor = SvgColorKeyword("lightseagreen")
    val LIGHT_SKY_BLUE: SvgColor = SvgColorKeyword("lightskyblue")
    val LIGHT_SLATE_GRAY: SvgColor = SvgColorKeyword("lightslategray")
    val LIGHT_SLATE_GREY: SvgColor = SvgColorKeyword("lightslategrey")
    val LIGHT_STEEL_BLUE: SvgColor = SvgColorKeyword("lightsteelblue")
    val LIGHT_YELLOW: SvgColor = SvgColorKeyword("lightyellow")
    val LIME: SvgColor = SvgColorKeyword("lime")
    val LIME_GREEN: SvgColor = SvgColorKeyword("limegreen")
    val LINEN: SvgColor = SvgColorKeyword("linen")
    val MAGENTA: SvgColor = SvgColorKeyword("magenta")
    val MAROON: SvgColor = SvgColorKeyword("maroon")
    val MEDIUM_AQUA_MARINE: SvgColor = SvgColorKeyword("mediumaquamarine")
    val MEDIUM_BLUE: SvgColor = SvgColorKeyword("mediumblue")
    val MEDIUM_ORCHID: SvgColor = SvgColorKeyword("mediumorchid")
    val MEDIUM_PURPLE: SvgColor = SvgColorKeyword("mediumpurple")
    val MEDIUM_SEAGREEN: SvgColor = SvgColorKeyword("mediumseagreen")
    val MEDIUM_SLATE_BLUE: SvgColor = SvgColorKeyword("mediumslateblue")
    val MEDIUM_SPRING_GREEN: SvgColor = SvgColorKeyword("mediumspringgreen")
    val MEDIUM_TURQUOISE: SvgColor = SvgColorKeyword("mediumturquoise")
    val MEDIUM_VIOLET_RED: SvgColor = SvgColorKeyword("mediumvioletred")
    val MIDNIGHT_BLUE: SvgColor = SvgColorKeyword("midnightblue")
    val MINT_CREAM: SvgColor = SvgColorKeyword("mintcream")
    val MISTY_ROSE: SvgColor = SvgColorKeyword("mistyrose")
    val MOCCASIN: SvgColor = SvgColorKeyword("moccasin")
    val NAVAJO_WHITE: SvgColor = SvgColorKeyword("navajowhite")
    val NAVY: SvgColor = SvgColorKeyword("navy")
    val OLD_LACE: SvgColor = SvgColorKeyword("oldlace")
    val OLIVE: SvgColor = SvgColorKeyword("olive")
    val OLIVE_DRAB: SvgColor = SvgColorKeyword("olivedrab")
    val ORANGE: SvgColor = SvgColorKeyword("orange")
    val ORANGE_RED: SvgColor = SvgColorKeyword("orangered")
    val ORCHID: SvgColor = SvgColorKeyword("orchid")
    val PALE_GOLDEN_ROD: SvgColor = SvgColorKeyword("palegoldenrod")
    val PALE_GREEN: SvgColor = SvgColorKeyword("palegreen")
    val PALE_TURQUOISE: SvgColor = SvgColorKeyword("paleturquoise")
    val PALE_VIOLET_RED: SvgColor = SvgColorKeyword("palevioletred")
    val PAPAYA_WHIP: SvgColor = SvgColorKeyword("papayawhip")
    val PEACH_PUFF: SvgColor = SvgColorKeyword("peachpuff")
    val PERU: SvgColor = SvgColorKeyword("peru")
    val PINK: SvgColor = SvgColorKeyword("pink")
    val PLUM: SvgColor = SvgColorKeyword("plum")
    val POWDER_BLUE: SvgColor = SvgColorKeyword("powderblue")
    val PURPLE: SvgColor = SvgColorKeyword("purple")
    val RED: SvgColor = SvgColorKeyword("red")
    val ROSY_BROWN: SvgColor = SvgColorKeyword("rosybrown")
    val ROYAL_BLUE: SvgColor = SvgColorKeyword("royalblue")
    val SADDLE_BROWN: SvgColor = SvgColorKeyword("saddlebrown")
    val SALMON: SvgColor = SvgColorKeyword("salmon")
    val SANDY_BROWN: SvgColor = SvgColorKeyword("sandybrown")
    val SEA_GREEN: SvgColor = SvgColorKeyword("seagreen")
    val SEASHELL: SvgColor = SvgColorKeyword("seashell")
    val SIENNA: SvgColor = SvgColorKeyword("sienna")
    val SILVER: SvgColor = SvgColorKeyword("silver")
    val SKY_BLUE: SvgColor = SvgColorKeyword("skyblue")
    val SLATE_BLUE: SvgColor = SvgColorKeyword("slateblue")
    val SLATE_GRAY: SvgColor = SvgColorKeyword("slategray")
    val SLATE_GREY: SvgColor = SvgColorKeyword("slategrey")
    val SNOW: SvgColor = SvgColorKeyword("snow")
    val SPRING_GREEN: SvgColor = SvgColorKeyword("springgreen")
    val STEEL_BLUE: SvgColor = SvgColorKeyword("steelblue")
    val TAN: SvgColor = SvgColorKeyword("tan")
    val TEAL: SvgColor = SvgColorKeyword("teal")
    val THISTLE: SvgColor = SvgColorKeyword("thistle")
    val TOMATO: SvgColor = SvgColorKeyword("tomato")
    val TURQUOISE: SvgColor = SvgColorKeyword("turquoise")
    val VIOLET: SvgColor = SvgColorKeyword("violet")
    val WHEAT: SvgColor = SvgColorKeyword("wheat")
    val WHITE: SvgColor = SvgColorKeyword("white")
    val WHITE_SMOKE: SvgColor = SvgColorKeyword("whitesmoke")
    val YELLOW: SvgColor = SvgColorKeyword("yellow")
    val YELLOW_GREEN: SvgColor = SvgColorKeyword("yellowgreen")

    val NONE: SvgColor = SvgColorKeyword("none")
    val CURRENT_COLOR: SvgColor = SvgColorKeyword("currentColor")


    fun create(r: Int, g: Int, b: Int): SvgColor {
        return SvgColorRgb(r, g, b)
    }

    fun create(color: Color?): SvgColor {
        return if (color == null) {
            NONE
        } else SvgColorRgb(color!!.getRed(), color!!.getGreen(), color!!.getBlue())
    }

    private class SvgColorRgb internal constructor(private val myR: Int, private val myG: Int, private val myB: Int) : SvgColor() {

        override fun toString(): String {
            return "rgb($myR,$myG,$myB)"
        }
    }

    private class SvgColorKeyword internal constructor(private val myLiteral: String) : SvgColor() {

        override fun toString(): String {
            return myLiteral
        }
    }
}