/*
 * Copyright (c) 2024. JetBrains s.r.o.
 * Use of this source code is governed by the MIT license that can be found in the LICENSE file.
 */

package org.jetbrains.letsPlot.core.plot.builder.assemble

// guide(name=None, title="...") is generated by python `labs()` function

class GuideTitleOption(title: String) : GuideOptions(title, isReverse = false) {

    override fun withTitle(title: String?): GuideTitleOption {
        return this
    }

    override fun withReverse(reverse: Boolean): GuideTitleOption {
        return this
    }
}