#!/usr/bin/env bash
#
# Must be run inside the manylinux docker container


set -e -x


working_dir="/tmp/python-package/"
dist_dir="dist/"
python_bin_version="cp3[7-9,10,11]*"

if [[ ${ARCH} = "arm64" ]]
then
  wheel_arch="aarch64"
elif [[ ${ARCH} = "x86_64" ]]
then
  wheel_arch=${ARCH}
fi

cd $working_dir


# Compile wheels
echo "Compile wheels..."
for pybin in /opt/python/${python_bin_version}/bin; do
    "${pybin}/pip" wheel ${working_dir} -w ${dist_dir}
done

# Bundle external shared libraries into the wheels
echo "Make auditwheel..."
for whl in ${dist_dir}lets_plot-*_${wheel_arch}.whl; do
    auditwheel repair "$whl" --plat ${PLAT} -w ${dist_dir}
done

# Remove source wheels with common platform tag
echo "Remove source wheels with common platform tag..."
shopt -s extglob
rm ${dist_dir}*-linux_*

echo "Remove dependent libraries generated by pip wheel..."
rm ${dist_dir}/pypng-*
rm ${dist_dir}/palettable-*

# Change folder ownership to user
echo "Return folder ownership to user..."
chown -R $USER_ID:$GROUP_ID ${working_dir}
echo "Finished for ${PLAT}"
